[kernel|esock|ttest] Make esock ttest (wrapper) scripts into shell script

diff --git a/lib/kernel/test/esock_ttest/esock-ttest-server-sock b/lib/kernel/test/esock_ttest/esock-ttest-server-sock
--- a/lib/kernel/test/esock_ttest/esock-ttest-server-sock
+++ b/lib/kernel/test/esock_ttest/esock-ttest-server-sock
@@ -20,37 +20,98 @@
 #  %CopyrightEnd%
 # 
 
+# Example:
+# Assuming your pwd is $ERL_TOP
+# (cd lib/kernel/test && ./esock_ttest/esock-ttest-server-sock [--active true --domain inet])
+
+program="`basename "$0"`"
+
 KERNEL=$ERL_TOP/lib/kernel
 KERNEL_TEST=$KERNEL/test
 ESOCK_TTEST=$KERNEL_TEST/esock_ttest
 
-#  $1 - async  - boolean()
-#  $2 - active - once | boolean()
-# [$3 - domain - inet (default) | inet6 | local]
-if [ $# -ge 2 ]; then
-
-    async=$1
-    active=$2
-
-    if [ $async = true ]; then
-	ASYNC="--async"
-    else
-	ASYNC=
-    fi
-
-    ACTIVE="--active $active"
-
-    if [ $# = 3 ]; then
-	DOMAIN="--domain $3"
-    fi
+ASYNC=
+ACTIVE=true
+DOMAIN=inet
+# PROFILE="--profile"
 
 
-else
-    echo "<ERROR> Missing args: async and active"
-    echo ""
-    exit 1
-fi
+######################################################################
+
+usage="\
+Usage: $program [options] 
+
+This shell script is used to run the esock ttest server part with
+'socket' as transport.
+
+Options:
+  --help              Display this help and exit.
+  --async             Asynchronous.
+  --active <active>   Active
+  	              once | boolean()
+                      Defaults to true
+  --domain <domain>   Domain of the transport
+  	   	      inet | inet6 | local
+  	              Defaults to 'inet'.
+"
+
+######################################################################
+
+now() { date '+%T'; }
+
+die () {
+    TIME=`now`
+    reason=$?
+    echo "ERROR [$TIME]: $@" >&2
+    echo "$usage"
+    exit $reason
+}
+
+while test $# != 0; do
+    # echo "arg $1"
+    case $1 in
+        --help)
+            echo "$usage" ; 
+            exit 0 ;;
+
+        --async)
+	    ASYNC="--async"
+            shift ;;
+
+        --active)
+	    shift ;
+	    TMP=$1
+	    if [ $TMP = once ]; then
+		ACTIVE=$TMP
+	    elif [ $TMP = true ]; then
+		ACTIVE=$TMP
+	    elif [ $TMP = false ]; then
+		ACTIVE=$TMP
+	    else
+		die "Invalid 'active' value '$TMP'";
+	    fi
+            shift ;;
+
+        --domain)
+	    shift ;
+	    TMP=$1
+	    if [ $TMP = inet ]; then
+		DOMAIN=$TMP
+	    elif [ $TMP = inet6 ]; then
+		DOMAIN=$TMP
+	    elif [ $TMP = inet6 ]; then
+		DOMAIN=$TMP
+	    else
+		die "Invalid 'domain' value '$TMP'";
+	    fi
+            shift ;;
+
+        *)
+            die "Unexpected option $1";
+            ;;
+    esac
+done
 
 
-$ESOCK_TTEST/esock-ttest --server $DOMAIN $ASYNC --transport sock $ACTIVE
+$ESOCK_TTEST/esock-ttest --server --domain $DOMAIN $ASYNC --transport sock --active $ACTIVE
 
