Run the smoke test for both SMP and non-SMP emulator

diff --git a/scripts/run-smoke-tests b/scripts/run-smoke-tests
--- a/scripts/run-smoke-tests
+++ b/scripts/run-smoke-tests
@@ -5,10 +5,17 @@ if [ -z "$ERL_TOP" ]; then
     ERL_TOP=$(pwd)
 fi
 
-cd $ERL_TOP/release/tests/test_server
-$ERL_TOP/bin/erl -s ts install -s ts smoke_test batch -s init stop
+function run_smoke_tests {
+    cd $ERL_TOP/release/tests/test_server
+    $ERL_TOP/bin/erl -s ts install -s ts smoke_test batch -s init stop
 
-if grep -q '=failed *[1-9]' ct_run.test_server@*/*/run.*/suite.log; then
-    echo "One or more tests failed."
-    exit 1
-fi
+    if grep -q '=failed *[1-9]' ct_run.test_server@*/*/run.*/suite.log; then
+        echo "One or more tests failed."
+        exit 1
+    fi
+    rm -rf ct_run.test_server@*
+}
+
+run_smoke_tests
+ERL_FLAGS="-smp disable" run_smoke_tests
+
