Serialize ex_doc download prompt and use native warnings_as_errors

diff --git a/make/check_ex_doc b/make/check_ex_doc
--- a/make/check_ex_doc
+++ b/make/check_ex_doc
@@ -4,7 +4,7 @@
 ##
 ## SPDX-License-Identifier: Apache-2.0
 ##
-## Copyright Ericsson AB 2024-2026. All Rights Reserved.
+## Copyright Ericsson AB 2026. All Rights Reserved.
 ##
 ## Licensed under the Apache License, Version 2.0 (the "License");
 ## you may not use this file except in compliance with the License.
@@ -20,19 +20,25 @@
 ##
 ## %CopyrightEnd%
 
-ARGS=("$@")
-
 ## If EX_DOC is not set to a file, we search the PATH for it using command -v
 if [ ! -f "${EX_DOC}" ]; then
    EX_DOC=$(command -v ex_doc)
 fi
 
-escript@EXEEXT@ "${EX_DOC}" "${ARGS[@]}"
-
-if [ "$?" != "0" ]; then
-    ## Touch the config file in order to re-trigger make
-    if [ -f "docs.exs" ]; then
-        touch "docs.exs"
+if [ -z "${EX_DOC}" ]; then
+    echo -n "Could not find ex_doc! "
+    read -p "Do you want to download latest ex_doc from github? (y/n)? " -n 1 -r
+    echo
+    if [[ $REPLY =~ ^[Yy]$ ]]
+    then
+        if $ERL_TOP/otp_build download_ex_doc; then
+            read -p "Press any key to continue..." -n 1 -r
+            echo "continuing"
+            EX_DOC=$(command -v ex_doc)
+        else
+            exit 1
+        fi
+    else
+        exit 1
     fi
-    exit 1;
 fi
